---

- name: Find redhat-rhui repos
  find:
    paths: /etc/yum.repos.d
    patterns: "redhat-rhui*"
  register: redhat_rhui

- name: Remove redhat-rhui repos
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ redhat_rhui['files'] }}"

- name: Create rhel-X-server-ose-rpms repo file
  template:
    src: "rhel-{{ major_platform_version }}-server-ose-{{ major_release_version }}.X-devel-rpms.repo.j2"
    dest: "/etc/yum.repos.d/rhel-{{ major_platform_version }}-server-ose-rpms.repo"
  notify: refresh cache
  when: openshift_deployment_type | default('openshift-enterprise') == 'openshift-enterprise'

- name: Create origin-repo repo file
  get_url:
    url: https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo
    dest: /etc/yum.repos.d/origin-repo.repo
  notify: refresh cache
  when: openshift_deployment_type | default('openshift-enterprise') == 'origin'

- name: Create rhel-X-server-rpms repo file
  template:
    src: "rhel-{{ major_platform_version }}-server-rpms.repo.j2"
    dest: "/etc/yum.repos.d/rhel-{{ major_platform_version }}-server-rpms.repo"
  notify: refresh cache
