---

- name: Find redhat-rhui repos
  find:
    paths: /etc/yum.repos.d
    patterns: "redhat-rhui*"
  register: redhat_rhui

- name: Remove redhat-rhui repos
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ redhat_rhui['files'] }}"

- name: Copy Atomic OpenShift yum repository certificate and key
  copy:
    src: "{{ ops_mirror_path }}"
    dest: /var/lib/yum/

- name: Create rhel-7-server-ose-rpms repo file
  template:
    src: rhel-7-server-ose-3.X-devel-rpms.repo.j2
    dest: /etc/yum.repos.d/rhel-7-server-ose-rpms.repo
  vars:
    target_version: "{{ prep_version }}"
  notify: refresh cache
  when: openshift_service_type == 'atomic-openshift'

- name: Create origin-repo repo file
  get_url:
    url: https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo
    dest: /etc/yum.repos.d/origin-repo.repo
  notify: refresh cache
  when: openshift_service_type == 'origin'

- name: Create rhel-7-server-rpms repo file
  copy:
    src: rhel-7-server-rpms.repo
    dest: /etc/yum.repos.d/
  notify: refresh cache
