---

- name: Create OpenShift Install Assets
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    aws_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    cluster_id: "{{ lookup('env', 'OPT_CLUSTER_ID') }}"
    cluster_dir: "/oa-testing/cluster"
    pull_secret_path: "/oa-testing/pull-secret.txt"
    private_key_path: "/oa-testing/openshift-dev.pem"

  tasks:
  ## Create install-config.yaml
  - name: Retrieve pull secret
    slurp:
      src: "{{ pull_secret_path }}"
    register: pull_secret
    no_log: true

  - name: Ensure proper permissions on private key file
    file:
      path: "{{ private_key_path }}"
      mode: 0600

  - name: Create public key from private key file
    command: >
      ssh-keygen -f {{ private_key_path }} -y
    register: keygen_output

  - name: Create Assets directory
    file:
      path: "{{ cluster_dir }}/assets"
      state: directory

  - name: Create install-config.yaml
    template:
      src: install-config.yaml.j2
      dest: "{{ cluster_dir }}/assets/install-config.yaml"
  ## install-config.yaml
