---

- name: Create OpenShift Install Assets
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    aws_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    cluster_id: "{{ lookup('env', 'OPT_CLUSTER_ID') }}"
    fips_enable: "{{ lookup('env', 'OPT_FIPS_ENABLE') | default(false, true) }}"
    pull_secret: "{{ lookup('file', '/oa-testing/pull-secret.txt') | from_json | to_json(separators=(',',':')) }}"
    cluster_dir: "/oa-testing/cluster"
    private_key_path: "{{ cluster_dir }}/assets/auth/id_ssh_rsa"
    public_key_path: "{{ cluster_dir }}/assets/auth/id_ssh_rsa.pub"
    public_key: "{{ lookup('file', '{{ public_key_path }}') }}"

  tasks:
  - name: Create Assets directory
    file:
      path: "{{ cluster_dir }}/assets"
      state: directory

  - name: Create a temporary ssh key pair
    openssh_keypair:
      path: "{{ private_key_path }}"

  - name: Create/Updata an EC2 key pair
    ec2_key:
      name: "{{ cluster_id }}"
      key_material: "{{ public_key }}"

  - name: Create install-config.yaml
    template:
      src: install-config.yaml.j2
      dest: "{{ cluster_dir }}/assets/install-config.yaml"
