---

- name: Provision AWS instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    aws_region: us-east-1
    cluster_id: "{{ lookup('env', 'OPT_CLUSTER_ID') }}"
    cluster_dir: "{{ lookup('env', 'OPT_CLUSTER_DIR') }}"
    aws_instance_file: "{{ cluster_dir }}/inventory/aws.json"
    aws_lb_instance_file: "{{ cluster_dir }}/inventory/awslb.json"
    aws_instance_type: "{{ lookup('env', 'OPT_INSTANCE_TYPE') | default('t2.medium') }}"
    master_count: "{{ lookup('env', 'OPT_MASTER_COUNT') | default(1)}}"
    compute_count: "{{ lookup('env', 'OPT_COMPUTE_COUNT') | default(0)}}"
    infra_count: "{{ lookup('env', 'OPT_INFRA_COUNT') | default(0)}}"
    lb_count: "{{ ( 1 if master_count | int > 1 else 0 )}}"
    cluster_count: "{{ master_count | int + compute_count | int + infra_count | int + lb_count | int }}"
    master_list: []
    compute_list: []
    infra_list: []
    lb_host: ''
    aws_volumes:
      - device_name: /dev/sda1
        volume_size: 50
        volume_type: gp2
        delete_on_termination: true
    platform_type: "{{ lookup('env', 'OPT_PLATFORM_TYPE') | default('rhel') }}"
    platform_type_dict:
      atomic:
        username: "cloud-user"
        owners: "309956199498"  # Red Hat, Inc.
        filters:
          name: "RHEL-Atomic_7.7*"
      centos:
        username: "centos"
        owners: "679593333241"
        filters:
          product-code: "aw0evgkw8e5c1q413zgy5pjce"  # CentOS-7 x86_64
      rhel:
        username: "ec2-user"
        owners: "309956199498"  # Red Hat, Inc.
        filters:
          name: "RHEL-7.7*Hourly*"
    platform_type_filter: "{{ platform_type_filter_dict[platform_type] }}"


  tasks:
  - name: Check for AWS Instance File
    stat:
      path: "{{ aws_instance_file }}"
    register: aws_instance_file_result

  - when: aws_instance_file_result.stat.exists
    block:
    - name: Existing AWS Instance File
      debug:
        msg: "Skipping provision, existing AWS Instance file found."
    - meta: end_play

  - import_tasks: tasks/lb_for_atomic.yml
    when:
    - master_count | int > 1
    - platform_type == 'atomic'

  - name: Find the most recently created AMI
    ec2_ami_facts:
      region: "{{ aws_region }}"
      owners: "{{ platform_type_dict[platform_type].owners }}"
      filters: "{{ platform_type_dict[platform_type].filters }}"
    register: ec2_ami_facts_results

  - name: Set aws_ami to most recent image
    set_fact:
      aws_ami: "{{ ec2_ami_facts_results.images[-1].image_id }}"

  - name: Set cluster count if Atomic
    set_fact:
      cluster_count: "{{ cluster_count|int - 1 }}"
    when: platform_type == 'atomic'

  - name: Create AWS Instances
    ec2:
      region: "{{ aws_region }}"
      key_name: "openshift-dev"
      instance_type: "{{ aws_instance_type }}"
      count: "{{ cluster_count }}"
      group_id:
        - sg-7e73221a  # default
        - sg-e1760186  # public-http
      vpc_subnet_id: "subnet-cf57c596"  # devenv-subnet-1
      image: "{{ aws_ami }}"
      volumes: "{{ aws_volumes }}"
      wait: yes
      instance_tags: "{{ {'kubernetes.io/cluster/' ~ cluster_id: 'owned', 'Name': cluster_id} }}"

    register: aws_instances

  - name: Save created AWS Instances
    copy:
      dest: "{{ aws_instance_file }}"
      content: "{{ aws_instances | to_nice_json }}"

  - name: Create list of masters
    set_fact:
      master_list: "{{ master_list + [ item ] }}"
    with_items:
    - "{{ aws_instances.instances[:master_count|int] }}"

  - name: Create list of compute
    set_fact:
      compute_list: "{{ compute_list + [ item ] }}"
    with_items:
    - "{{ aws_instances.instances[master_count|int:master_count|int+compute_count|int] }}"

  - name: Create list of infra
    set_fact:
      infra_list: "{{ infra_list + [ item ] }}"
    with_items:
    - "{{ aws_instances.instances[master_count|int+compute_count|int:master_count|int+compute_count|int+infra_count|int] }}"

  - name: Create lb_host
    set_fact:
      lb_host: "{{ aws_instances.instances[-1] }}"
    when:
    - master_count | int > 1
    - platform_type != 'atomic'

  - name: Create Ansible Inventory File
    template:
      src: hosts.j2
      dest: "{{ cluster_dir }}/inventory/hosts"
