---

- name: Terminate AWS instances
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    aws_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
    cluster_id: "{{ lookup('env', 'OPT_CLUSTER_ID') }}"
    cluster_dir: "/oa-testing/cluster"
    aws_instances_file: "{{ cluster_dir }}/inventory/aws.json"
    aws_lb_instance_file: "{{ cluster_dir }}/inventory/awslb.json"
    platform_type: "{{ lookup('env', 'OPT_PLATFORM_TYPE') | default('rhel', true) }}"

  tasks:
  - name: Set aws_region from .aws/config file
    set_fact:
      aws_region: "{{ lookup('ini', 'region section=profile\ openshift-dev file=~/.aws/config') }}"
    when: aws_region == ""

  - import_tasks: tasks/terminate.yml
    vars:
      aws_instance_file: "{{ aws_instances_file }}"

  - import_tasks: tasks/terminate.yml
    vars:
      aws_instance_file: "{{ aws_lb_instance_file }}"
    when: platform_type == 'atomic'
